handle sql errors for empty fields
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

problem is that empty (or missing) fields are somewhy '[]' not 'None' on rpm5